; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = USB_MIDI
;default_envs = USB_MIDI_SERIAL

[env]
platform = teensy
framework = arduino
board = teensy40
board_build.f_cpu = 600000000L
monitor_port = /dev/ttyACM0
monitor_speed = 230400
lib_deps =
	;bblanchon/ArduinoJson @ ^6.21.5
	bblanchon/ArduinoJson @ ^7.0.4
	;https://github.com/thomasfredericks/Bounce2

[env:USB_MIDI]
build_flags = 
	-DUSB_MIDI
	-DBLOB_VELOCITY
	-DTEENSY_OPT_FASTEST
	;-DRUNING_MEDIAN
[env:USB_MIDI_SERIAL]
build_flags =
	-DBLOB_VELOCITY
	-DTEENSY_OPT_FASTEST
	;-DRUNING_MEDIAN
	-DUSB_MIDI_SERIAL
	
 	;-DDEBUG_FPS        ; Print Frames Per Second (last test is 586 fps)
 	;-DDEBUG_ENCODER    ; Print encoder value
 	;-DDEBUG_BUTTONS    ; Print buttons states
 	;-DDEBUG_MODES      ;    
 	;-DDEBUG_LEVELS     ;
 	;-DDEBUG_ADC        ; Print 16x16 Analog raw values
 	;-DDEBUG_INTERP     ; Print 64x64 interpolated values
 	;-DDEBUG_BITMAP     ; Print 64x64 binary image based on threshold
	;-DDEBUG_LLIST		;
 	;-DDEBUG_FIND_BLOBS ; Print lowlevel blobs values
	;-DDEBUG_BLOBS_STATUS; 
 	;-DDEBUG_BLOBS      ; Print blobs values
 	;-DDEBUG_MIDI_IO    ;
 	;-DDEBUG_CONFIG     ;
	
	;-DDEBUG_MAPPINGS_SWITCHS   ; Print switchs GUI values
	;-DDEBUG_MAPPINGS_SLIDERS 	; Print slider GUI values
	;-DDEBUG_MAPPINGS_KNOBS 	; Print knobs GUI values
	;-DDEBUG_MAPPINGS_TOUCHPADS ; Print touchpads GUI values
	;-DDEBUG_MAPPINGS_POLYGONS	; Print polygons GUI values
